### ISSUE TITLE
grimblast area suggestions

### ISSUE THREAD

**Issue by MatthiasGrandl** [hyprwm/contrib#23]
it would be nice if the grimblast area selection would be keyboard controllable.

here is what I imagine:
- enter to screenshot the currently selected window
- arrows/hjkl to select other windows without using the mouse

also potentially a good idea would be to switch between area and window selection by pressing space (that is how it works in the MacOS screenshot utility). I know it has just been combined, but in my opinion it is strictly speaking worse in terms of accessibility. multiple times now I screenshotted a tiny (like 2x2) area because my click got interpretted as a drag on a hidpi display. let me know what you think. I might just try and implement some of those suggestions myself.

**Comment by fufexan** [comment]
This is not possible due to how slurp works. Keyboard arrows/enter/hjkl aren't interpreted in any way by slurp. Space is used to move the entire selected area.

So there isn't any way of switching between modes or doing anything that you propose while we're using slurp.

If you do come up with a better solution, I'd be happy to hear it.

**Comment by MatthiasGrandl** [comment]
Ah that's true... guess without forking slurp this won't work out then. I'll close the issue then.
